version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: root 
    ports:
      - "3308:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/novel_app
    ports:
      - "3009:3000"
    links:
      - db
    environment:
      TZ: "Asia/Tokyo"
