default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  REDIS_URL: redis://redis:6379

development:
  <<: *default
  database: novel_app_development

test:
  <<: *default
  database: novel_app_test

production:
  <<: *default
  database: novel_app_production
  username: novel_app
  password: <%= ENV['NOVEL_APP_DATABASE_PASSWORD'] %>
  pool: 5
